#!/usr/bin/env bash
set -euo pipefail

# Forge local services setup.
#
# One pass: create the workspace env file if needed, start PostgreSQL and Redis with Docker,
# install web dependencies, run database migrations, and seed the agents.
# After this finishes you can go straight to `cd web && npm run dev`.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

expand_home_path() {
  case "${1:-}" in
    "~") [ -n "${HOME:-}" ] && printf '%s\n' "$HOME" ;;
    "~/"*) [ -n "${HOME:-}" ] && printf '%s/%s\n' "$HOME" "${1#\~/}" ;;
    *) printf '%s\n' "$1" ;;
  esac
}

workspace_root() {
  local root settings_file
  root="${FORGE_WORKSPACE_ROOT:-}"
  if [ -z "$root" ] && [ -n "${HOME:-}" ]; then
    settings_file="$HOME/Documents/Forge/global-settings.json"
    if [ -f "$settings_file" ]; then
      root="$(sed -n 's/^[[:space:]]*"workspaceRoot"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$settings_file" | head -n1)"
    fi
  fi
  [ -n "$root" ] || root="~/Documents/Forge"
  expand_home_path "$root"
}

WORKSPACE_ROOT="$(workspace_root)"
ENV_FILE="${FORGE_ENV_FILE:-$WORKSPACE_ROOT/config/forge.env}"

bold() { printf '\033[1m%s\033[0m\n' "$1"; }
step() { printf '\n\033[1;36m==>\033[0m \033[1m%s\033[0m\n' "$1"; }
info() { printf '    %s\n' "$1"; }
die()  { printf '\033[1;31mERROR:\033[0m %s\n' "$1" >&2; exit 1; }

random_hex() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex "$1"
    return 0
  fi
  node -e "console.log(require('crypto').randomBytes(Number(process.argv[1])).toString('hex'))" "$1"
}

bold "Forge local services setup"
info "This starts PostgreSQL and Redis and prepares the web app in one pass."

cd "$REPO_ROOT"

if ! command -v docker >/dev/null 2>&1; then
  die "Docker is not installed. Install Docker Desktop or Docker Engine, then run this again."
fi

if docker compose version >/dev/null 2>&1; then
  COMPOSE=(docker compose)
elif command -v docker-compose >/dev/null 2>&1; then
  COMPOSE=(docker-compose)
else
  die "Docker Compose is not available. Install the Docker Compose plugin or docker-compose."
fi

if ! command -v node >/dev/null 2>&1; then
  die "Node.js is not installed. Install Node 22 or newer, then run this again."
fi
NODE_MAJOR="$(node -p 'process.versions.node.split(".")[0]' 2>/dev/null || echo 0)"
if [ "$NODE_MAJOR" -lt 22 ]; then
  die "Node $(node -v) is too old. Forge needs Node 22 or newer."
fi

# Create the env file if it does not exist. We do NOT exit afterwards: the rest
# of setup runs in the same pass so there is nothing to re-run by hand.
if [ ! -f "$ENV_FILE" ]; then
  DB_PASSWORD="$(random_hex 16)"
  SESSION_SECRET="$(random_hex 32)"
  mkdir -p "$(dirname "$ENV_FILE")"
  {
    printf '# Generated by scripts/setup.sh. Provider API keys are entered in the Forge web UI.\n'
    printf 'POSTGRES_USER=forge\n'
    printf 'POSTGRES_PASSWORD=%s\n' "$DB_PASSWORD"
    printf 'POSTGRES_DB=forge\n'
    printf 'DATABASE_URL=postgresql://forge:%s@localhost:5432/forge\n' "$DB_PASSWORD"
    printf 'REDIS_URL=redis://localhost:6379/0\n'
    printf 'NEXT_PUBLIC_APP_URL=http://localhost:3000\n'
    printf 'NEXT_TELEMETRY_DISABLED=1\n'
    printf 'FORGE_EMBED_WORKER=1\n'
    printf 'FORGE_AGENT_WEB_SEARCH=1\n'
    printf 'FORGE_WORKER_CLAIM_TIMEOUT_SECONDS=5\n'
    printf 'FORGE_PASSKEYS_ENABLED=1\n'
    printf 'FORGE_TRUST_PROXY=0\n'
    printf 'SESSION_SECRET=%s\n' "$SESSION_SECRET"
    printf 'WEBAUTHN_RP_ID=localhost\n'
    printf 'WEBAUTHN_RP_NAME=Forge\n'
    printf 'WEBAUTHN_ORIGIN=http://localhost:3000\n'
  } > "$ENV_FILE"
  chmod 600 "$ENV_FILE"
  step "Created $ENV_FILE"
  info "Defaults target local Docker PostgreSQL and Redis and work as-is."
  info "Provider API keys are optional here — add them later in the Forge web UI."
else
  step "Using existing $ENV_FILE"
fi

# Start infrastructure
step "Starting PostgreSQL and Redis"
info "Docker will download the images the first time. Later runs are much faster."
FORGE_WORKSPACE_ROOT="$WORKSPACE_ROOT" "${COMPOSE[@]}" --env-file "$ENV_FILE" up -d --wait postgres redis

step "Infrastructure ready"
info "PostgreSQL: localhost:5432"
info "Redis:      localhost:6379"

# Prepare the web app: install dependencies, migrate the database, seed agents.
step "Installing web dependencies"
info "npm install can take a few minutes on the first run."
(cd web && npm install --loglevel=error --no-audit --no-fund)

step "Applying database migrations"
(cd web && FORGE_WORKSPACE_ROOT="$WORKSPACE_ROOT" FORGE_ENV_FILE="$ENV_FILE" npm run db:migrate)

step "Seeding agent configurations"
(cd web && FORGE_WORKSPACE_ROOT="$WORKSPACE_ROOT" FORGE_ENV_FILE="$ENV_FILE" npm run db:seed-agents)

step "Setup complete"
info "Start Forge with: cd web && npm run dev"
info "Then open http://localhost:3000 and create the first account."
info "The web UI starts the task worker automatically unless FORGE_EMBED_WORKER=0."
